name: Create Release

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/workflows/**' 

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Read version
        id: get_version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Zip Game folder
        run: |
          zip -r "v${{ env.VERSION }}.zip" Game

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "v${{ env.VERSION }}"
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./v${{ env.VERSION }}.zip"
          asset_name: "v${{ env.VERSION }}.zip"
          asset_content_type: application/zip
